config/routes.rb
Rails.application.routes.draw do
  # rootの設定
  root "questions#index"
  # CRUDを設定する
  resources :questions do
    resources :answers
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
    has_many :answers, dependent: :destroy

    validates :title, presence: true
    validates :name, presence: true
    validates :body, presence: true, length: {minimum: 5}
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  # 回答の投稿
  def create
    @question = Question.find(params[:question_id])
    @question.answers.create(answer_params)
    redirect_to question_path(@question)
  end
  # 回答の削除
  def destroy
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.destroy
    # :see_otherはHTTPステータスコードの303を意味する
    redirect_to @question, status: :see_other
  end

  private
  def answer_params
    params.require(:answer).permit(:name, :ans_body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # 質問一覧
  def index
    @questions = Question.all

  end
  # 質問詳細
  def show
    @question = Question.find(params[:id])

  end
  # 質問作成
  def new
    @question = Question.new
  end
  # 質問登録
  def create
    # モデルの初期化
      @question = Question.new(question_params)
    # DBへ保存
    if @question.save
      # 詳細ページへ移動
      redirect_to @question
    else
      render "new", status: :unprocessable_entity
    end
  end
  # 質問編集
  def edit
    @question = Question.find(params[:id])
  end
  # 質問更新
  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to @question
    else
      render "edit", status: :unprocessable_entity
    end
  end
  # 質問削除
  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end

  private
  def question_params
    params.require(:question).permit(:title, :name, :body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qanda</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_with model:@question do |f| %>
  <% if @question.errors.any? %>
    <div>
      <ul>
        <% @question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>編集ページ</h1>
<%= render partial: "form" %>

app/views/questions/index.html.erb
<h1>質問一覧</h1>
<%= link_to "new", new_question_path %>
<table>
  <tr>
    <th>ID</th>
    <th>Title</th>
    <th>Name</th>
    <th>Text</th>
    <th></th>
  </tr>
  <% @questions.each do |question| %>
    <tr>
      <td><%= question.id %></td>
      <td><%= question.title %></td>
      <td><%= question.name %></td>
      <td><%= question.body %></td>
      <td><%= link_to "show", question_path(question) %></td>
      <td><%= link_to "edit", edit_question_path(question) %></td>
      <td><%= link_to "destroy", question_path(question), method: :delete, data: {confirm: "Are you sure?" } %></td>
    </tr>
  <% end %>

</table>

app/views/questions/new.html.erb
<h1>新規の質問</h1>
<%= render partial: "form" %> 

app/views/questions/show.html.erb
<h1>詳細ページ</h1>

<p>
  Title:<br>
  <%= @question.title %>
</p>

<p>
  Name:<br>
  <%= @question.name %>
</p>

<p>
  Body:<br>
  <%= @question.body %>
</p>

<h2>回答一覧</h2>
<% @question.answers.each do |answer| %>
  <p>
    名前：<br>
    <%= answer.name %>
  </p>
  <p>
    回答本文：<br>
    <%= answer.ans_body %><br>
    <%= link_to "destroy answer", [answer.question, answer], method: :delete, data: {confirm: "Are you sure?" } %>
  </p>
<% end %>



<h2>回答</h2>
<%= form_with model:[@question, @question.answers.build] do |f| %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :ans_body %><br>
    <%= f.text_area :ans_body %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>
<%= link_to "top", questions_path %>